# name: Django Deploy

# on:
#   workflow_call:
#   workflow_dispatch:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:latest
#         env:
#           POSTGRES_USER: arturo_moreno
#           POSTGRES_PASSWORD: "1234"
#           POSTGRES_DB: arturo_morenodb
#         ports:
#           - 5541:5541
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#     steps:
#       - name: Checkout changes on github
#         uses: actions/checkout@v2
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Run migrations
#         run: python manage.py migrate
#       - name: Run tests
#         run: pytest